Rebase sep 2020 f3558c7
brave/omaha pull request #29
Opened 2020-09-02 06:46 UTC by simonhong

Rebase onto latest f3558c7

2020-09-07 12:01 UTC, mherrmann commented
@simonhong and @mihaiplesa asked me to conduct a review of those changes. I will document my observations here, in individual comments.

Simon uploaded `BraveBrowserSetup.exe` to Slack on Friday. As I understand, this is a tagged meta installer produced from the rebased Omaha version.

When I install Brave with this installer, I get the following assertion error upon every start of Windows. The test machine in this case is Windows 7.

![image](https://user-images.githubusercontent.com/1076393/92385664-92092680-f112-11ea-9b79-7d25122a1bdc.png)

2020-09-07 12:04 UTC, mherrmann commented
I get the following assertion error followed by several occurrences of the one in my previous comment when performing a clean install with `BraveBrowserSetup.exe`.

![image](https://user-images.githubusercontent.com/1076393/92385852-eb715580-f112-11ea-9825-61ffc5316cd3.png)

2020-09-07 13:01 UTC, mherrmann commented
The code changes (commits `4f7963..4af3e1` which are on top of Google's current `f3558c`) look fine to me. I still want to look into

- [ ] whether any code changes (from my experience) may be missing
- [ ] failing unit tests.

Will report on this below too.

2020-09-08 01:14 UTC, simonhong commented
I'm investigating about empty version string assert. Not sure but maybe our code queries version string before version is initialized. Looking now...

2020-09-08 01:24 UTC, simonhong commented
@mherrmann  Regarding to the assert comes from `HKEY_USERS\\.DEFAULT\\Software\\Google\\Update`, below code causes it.
According to the comments, this regkey seems not used anymore(deprecated) and just deleting it will fix.
Also, this reg key is google's key not our key. I assume you have this key from your old chrome install?
IMO, we can ignore this or just deleting this key manually would be fine.
```
  // Bug 994348 does not repro anymore.
  // If the assert fires, clean up the key, and fix the code if we have unit
  // tests or application code that create the key.
  ASSERT(!RegKey::HasKey(_T("HKEY_USERS\\.DEFAULT\\Software\\Google\\Update")),
         (_T("This assert has fired because it has found the registry key at ")
          _T("'HKEY_USERS\\.DEFAULT\\Software\\Google\\Update'. ")
          _T("Please delete the key and report to omaha-core team if ")
          _T("the assert fires again.")));
```

2020-09-08 03:19 UTC, simonhong commented
One more observation is shell executable in root omaha directory is not update when I run newer version if stub(meta) installer.
If I have already installed 1.3.99 installer, and run rebased installer(1.3.101),
Shell(`Program Files(x86)/BraveSoftware/Update/BraveUpdate.exe`) in root folder is not updated.
But Shell in versioned directory (Program Files(x86)/BraveSoftware/Update/1.3.101.0/) is updated to latest (1.3.101).

I think this is not an issue because shell(`BraveUpdate.exe`) is very tiny program that just loading latest `goopdate.dll` from `1.3.101`.

2020-09-08 05:28 UTC, mherrmann commented
@simonhong I'm starting to look at code modifications I normally make when forking Omaha.

One thing that immediately came up is that I have `KEY_USERS\\.DEFAULT\\Software\\*OMAHACOMPANYNAME*\\Update`. I suspect the assertion can be fixed if you replace the string `...\Google\Update` by `...\BraveSoftware\Update`. There may of course also be many other similar cases.

2020-09-08 08:29 UTC, mherrmann commented
@simonhong I've compared your fork with the changes I normally make. I committed interesting differences to [mherrmann/omaha-brave@suggestions_for_rebase_46517d](https://github.com/mherrmann/omaha-brave/tree/suggestions_for_rebase_46517d). I did not test these changes; I think the best approach would be for you to go through them and decide whether they make sense for you.

2020-09-08 08:39 UTC, mherrmann commented
As a preliminary summary of my review, here is what I would suggest:

- [ ] Fix the [failing assertion `HasKey(_T("HKEY_USERS\\.DEFAULT\\Software\\Google\\Update"))`](https://github.com/brave/omaha/pull/29#issuecomment-688279759). This is likely already done via Simon's commit 46517d5.
- [ ] Fix (or disable in the specific case where it occurs) the [failing assertion `!version_str.isEmpty`](https://github.com/brave/omaha/pull/29#issuecomment-688281565).
- [ ] Selectively apply those [changes in my fork](https://github.com/brave/omaha/pull/29#issuecomment-688710040) that you feel make sense for Brave.
- [ ] Fix all failing unit tests.

With those tasks completed, I think it would be safe to release the rebased Omaha version to a test group or otherwise small percentage of users.

If I should help with any of these, please just let me know.

2020-09-09 11:49 UTC, mherrmann commented
@simonhong you requested a review here; Was that merely to document that I performed a review, or do you want me to look into something?

2020-09-09 13:04 UTC, simonhong commented
@mherrmann I just wanted to put your name in reviewer list :)

2020-09-10 03:22 UTC, simonhong commented
I got below unit test result. 113 tests are failed from 3496.
A lot of failure comes from customization like url, branding change.
I'm not sure correcting all failed tests is worth to do it.
@mherrmann can you check we have critical test failure?

```
C:\PRJ\omaha\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_brief=1

Pinging 2.2.2.2 with 32 bytes of data:

gingin
 P.i2n.g2i.n2g  2.2w.i2t.h2  32 bywtietsh  o3f2  dbayttae:s
f data:

iing
tPing i2n.g2 .22..22. 2.2 withw i3t2h  b3y2t ebsy toefs  doaft ad:a
:

Pinging 2.2.2.2 with 32 bytes of data:
base\time_unittest.cc(143): error: Expected equality of these values:
  time.wDay
    Which is: 17
  16
[  FAILED  ] TimeTest.RFC822TimeParsing (1 ms)
base\user_rights_unittest.cc(28): error: Expected: (UserRights::UserIsLoggedOnInteractively(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

base\user_rights_unittest.cc(29): error: Value of: is_logged_on
  Actual: false
Expected: true
[  FAILED  ] UserRightsTest.UserIsLoggedOnInteractively (9 ms)
        This test needs to be run separately. Set 'TEST_GETFOLDERPATH_PROGRAMFILES_REGISTRYREDIRECTION' in the environment, then run it separately.
base\utils_unittest.cc(148): error: Expected equality of these values:
  9405
  buffer.size()
    Which is: 9514
[  FAILED  ] UtilsTest.ReadEntireFile (14 ms)
base\utils_unittest.cc(383): error: Expected: (IsUserLoggedOn(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

[  FAILED  ] UtilsTest.IsUserLoggedOn (2 ms)
client\help_url_builder_test.cc(382): error: Expected equality of these values:
  kExpectedUrlBegin
    Which is: L"https://www.google.com/support/installer/?hl=en-GB&product=%7Btest-user-app-id%7D&error=0x80004005&extra_code=-2147418113&guver=5.6.7.8&m=0&os="
  url.Left(kExpectedUrlBegin.GetLength())
    Which is: L"https://support.brave.com/"
client\help_url_builder_test.cc(383): error: Expected: (-1) != (url.Find(kExpectedUrlAfterOs)), actual: -1 vs -1
iid=&brand=&source=gethelp&testsource=
 not found in
https://support.brave.com/
[  FAILED  ] HelpUrlBuilderTest.BuildGetHelpUrl_User (4 ms)
client\help_url_builder_test.cc(414): error: Expected equality of these values:
  kExpectedUrlBegin
    Which is: L"https://www.google.com/support/installer/?hl=en-GB&product=%7Btest-machine-app-id%7D&error=0x80004004&extra_code=99&guver=5.6.7.8&m=1&os="
  url.Left(kExpectedUrlBegin.GetLength())
    Which is: L"https://support.brave.com/"
client\help_url_builder_test.cc(415): error: Expected: (-1) != (url.Find(kExpectedUrlAfterOs)), actual: -1 vs -1
iid=%7B326ADA1D-06AA-4C16-8101-5FC3FEBC852A%7D&brand=GOOG&source=gethelp&testsource=
 not found in
https://support.brave.com/
[  FAILED  ] HelpUrlBuilderTest.BuildGetHelpUrl_Machine (2 ms)
client\help_url_builder_test.cc(446): error: Expected equality of these values:
  kExpectedUrlBegin
    Which is: L"https://www.google.com/support/installer/?hl=en-GB&product=AppName&error=1666&from_extra_code=1&guver=5.6.7.8&m=1&os="
  url.Left(kExpectedUrlBegin.GetLength())
    Which is: L"https://support.brave.com/"
client\help_url_builder_test.cc(447): error: Expected: (-1) != (url.Find(kExpectedUrlAfterOs)), actual: -1 vs -1
iid=%7B326ADA1D-06AA-4C16-8101-5FC3FEBC852A%7D&brand=GOOG&source=gethelp&testsource=
 not found in
https://support.brave.com/
[  FAILED  ] HelpUrlBuilderTest.BuildGetHelpUrl_InstallerErrorWithExtraCode (2 ms)
client\help_url_builder_test.cc(479): error: Expected equality of these values:
  kExpectedUrlBegin
    Which is: L"https://www.google.com/support/installer/?hl=en-GB&product=AppName&error=0x80040902&extra_code=0&guver=5.6.7.8&m=1&os="
  url.Left(kExpectedUrlBegin.GetLength())
    Which is: L"https://support.brave.com/"
client\help_url_builder_test.cc(480): error: Expected: (-1) != (url.Find(kExpectedUrlAfterOs)), actual: -1 vs -1
iid=%7B326ADA1D-06AA-4C16-8101-5FC3FEBC852A%7D&brand=GOOG&source=gethelp&testsource=
 not found in
https://support.brave.com/
[  FAILED  ] HelpUrlBuilderTest.BuildGetHelpUrl_InstallerErrorWithoutExtraCode (2 ms)
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because OS is Vista or later.
C:\PRJ\omaha\omaha/testing/unittest_debug_helper.h(136): error: Expected: (g_assert_count) > (old_assert_count_), actual: 21 vs 21
This test was expected to trigger at least one assert.
[  FAILED  ] CommandLineBuilder.BuildUpdateAndGetCommandLineWithGoogleUpdateExe (2 ms)
common\goopdate_utils_unittest.cc(1228): error: File::Copy(shell_path_1_2_183_21, goopdate_exe, true) failed with error 0x80070002
common\goopdate_utils_unittest.cc(1230): error: Expected equality of these values:
  L"1.2.183.21"
  GetInstalledShellVersion(true)
    Which is: L""
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_ShellExists (3 ms)
common\goopdate_utils_unittest.cc(1247): error: File::Copy(shell_path_1_2_183_21, goopdate_exe, true) failed with error 0x80070002
common\goopdate_utils_unittest.cc(1249): error: Expected equality of these values:
  L"1.2.183.21"
  GetInstalledShellVersion(false)
    Which is: L""
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_User_ShellExists (2 ms)
common\goopdate_utils_unittest.cc(1113): error: Expected equality of these values:
  program_files_path + L"\\" + L"BraveSoftware" + L"\\" + L"Update" + L"\\GoogleUpdate.exe"
    Which is: L"C:\\Program Files (x86)\\BraveSoftware\\Update\\GoogleUpdate.exe"
  path
    Which is: L"C:\\Program Files (x86)\\BraveSoftware\\Update\\BraveUpdate.exe"
[  FAILED  ] GoopdateUtilsRegistryProtectedWithMachineFolderPathsTest.BuildGoogleUpdateExePath_MachineVersionFound (2 ms)
common\goopdate_utils_unittest.cc(1124): error: Expected equality of these values:
  program_files_path + L"\\" + L"BraveSoftware" + L"\\" + L"Update" + L"\\GoogleUpdate.exe"
    Which is: L"C:\\Program Files (x86)\\BraveSoftware\\Update\\GoogleUpdate.exe"
  path
    Which is: L"C:\\Program Files (x86)\\BraveSoftware\\Update\\BraveUpdate.exe"
common\goopdate_utils_unittest.cc(1131): error: Expected equality of these values:
  program_files_path + L"\\" + L"BraveSoftware" + L"\\" + L"Update" + L"\\GoogleUpdate.exe"
    Which is: L"C:\\Program Files (x86)\\BraveSoftware\\Update\\GoogleUpdate.exe"
  path
    Which is: L"C:\\Program Files (x86)\\BraveSoftware\\Update\\BraveUpdate.exe"
[  FAILED  ] GoopdateUtilsRegistryProtectedWithMachineFolderPathsTest.BuildGoogleUpdateExePath_MachineVersionNotFound (4 ms)
common\goopdate_utils_unittest.cc(1149): error: Expected equality of these values:
  expected_path
    Which is: L"C:\\Users\\hongy\\AppData\\Local\\BraveSoftware\\Update\\GoogleUpdate.exe"
  path
    Which is: L"C:\\Users\\hongy\\AppData\\Local\\BraveSoftware\\Update\\BraveUpdate.exe"
[  FAILED  ] GoopdateUtilsRegistryProtectedWithUserFolderPathsTest.BuildGoogleUpdateExePath_UserVersionFound (2 ms)
common\goopdate_utils_unittest.cc(1163): error: Expected equality of these values:
  expected_path
    Which is: L"C:\\Users\\hongy\\AppData\\Local\\BraveSoftware\\Update\\GoogleUpdate.exe"
  path
    Which is: L"C:\\Users\\hongy\\AppData\\Local\\BraveSoftware\\Update\\BraveUpdate.exe"
common\goopdate_utils_unittest.cc(1168): error: Expected equality of these values:
  expected_path
    Which is: L"C:\\Users\\hongy\\AppData\\Local\\BraveSoftware\\Update\\GoogleUpdate.exe"
  path
    Which is: L"C:\\Users\\hongy\\AppData\\Local\\BraveSoftware\\Update\\BraveUpdate.exe"
[  FAILED  ] GoopdateUtilsRegistryProtectedWithUserFolderPathsTest.BuildGoogleUpdateExePath_UserVersionNotFound (2 ms)
        Test did not run because the user IS an admin.
comm [...]

2020-09-10 06:47 UTC, simonhong commented
And this is the test result of upstream. 21 tests are failed.
```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_brief=1

Pinging 2.2.2.2 with 32 bytes of data:

.2nging 2.2
 P ingiwnigt h2 .322. 2b.y2t es ofw idtaht a3:2
ytes of data:

ningi
f2P.i2n.g2i.n2g  2.2.w2i.t2h  32 wbiytthe s3 2o fb ydtaetsa :o
data:

Pinging 2.2.2.2 with 32 bytes of data:
base\time_unittest.cc(143): error: Expected equality of these values:
  time.wDay
    Which is: 17
  16
[  FAILED  ] TimeTest.RFC822TimeParsing (1 ms)
base\user_rights_unittest.cc(28): error: Expected: (UserRights::UserIsLoggedOnInteractively(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

base\user_rights_unittest.cc(29): error: Value of: is_logged_on
  Actual: false
Expected: true
[  FAILED  ] UserRightsTest.UserIsLoggedOnInteractively (7 ms)
        This test needs to be run separately. Set 'TEST_GETFOLDERPATH_PROGRAMFILES_REGISTRYREDIRECTION' in the environment, then run it separately.
base\utils_unittest.cc(383): error: Expected: (IsUserLoggedOn(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

[  FAILED  ] UtilsTest.IsUserLoggedOn (2 ms)
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because OS is Vista or later.
common\goopdate_utils_unittest.cc(1218): error: Expected equality of these values:
  shell_version
    Which is: 281487868100608
  0ULL
    Which is: 0
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell (1 ms)
common\goopdate_utils_unittest.cc(1228): error: File::Copy(shell_path_1_2_183_21, goopdate_exe, true) failed with error 0x80070020
common\goopdate_utils_unittest.cc(1230): error: Expected equality of these values:
  L"1.2.183.21"
  GetInstalledShellVersion(true)
    Which is: L"1.3.99.0"
common\goopdate_utils_unittest.cc(1231): error: File::Remove(goopdate_exe) failed with error 0x80070005
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_ShellExists (6 ms)
        Test did not run because the user IS an admin.
common\omaha_customization_unittest.cc(350): error: Value of: ConfigManager::Instance()->IsInternalUser()
  Actual: false
Expected: true
[  FAILED  ] OmahaCustomizationTest.IsInternalUser (2 ms)
        Test did not run because this OS supports the Task Scheduler 2.0 API.
Hello World
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test is only meaningful when the unit test is run as the SYSTEM account.
goopdate\download_manager_unittest.cc(216): error: Expected: (-1) != (actual_pings.Find( L"eventtype=1, eventresult=1, errorcode=0, extracode1=0, " L"url=http://dl.google.com/update2/UpdateData.bin, " L"downloader=bits, error=0x0, downloaded_bytes=2048, " L"total_bytes=2048, download_time=")), actual: -1 vs -1
goopdate\download_manager_unittest.cc(222): error: Expected: (-1) != (actual_pings.Find( L"eventtype=1, eventresult=1, errorcode=0, extracode1=0, " L"url=http://dl.google.com/update2/UpdateData1.bin, " L"downloader=bits, error=0x0, downloaded_bytes=2048, " L"total_bytes=2048, download_time=")), actual: -1 vs -1
[  FAILED  ] DownloadManagerUserTest.DownloadApp_MultiplePackagesInOneApp (12784 ms)
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
goopdate\worker_unittest.cc(623): error: Expected equality of these values:
  STATE_UPDATE_AVAILABLE
    Which is: 4
  app1_->state()
    Which is: 17
[  FAILED  ] WorkerWithTwoAppsTest.CheckForUpdateAsync_Large (749 ms)
goopdate\worker_unittest.cc(643): error: Expected equality of these values:
  STATE_UPDATE_AVAILABLE
    Which is: 4
  app1_->state()
    Which is: 17
goopdate\worker_unittest.cc(651): error: Expected equality of these values:
  STATE_WAITING_TO_DOWNLOAD
    Which is: 5
  app1_->state()
    Which is: 17
goopdate\worker_unittest.cc(660): error: Expected equality of these values:
  STATE_READY_TO_INSTALL
    Which is: 11
  app1_->state()
    Which is: 17
[  FAILED  ] WorkerWithTwoAppsTest.DownloadAsyncThenDownloadAndInstallAsync_Large (18263 ms)
GetFileVersionInfoSize failed with error 2.
recovery\client\google_update_recovery_unittest.cc(738): error: Expected: (VerifyFileSignature(executable_full_path)) succeeds.
  Actual: 0x80096005 The timestamp signature and/or certificate could not be verified or is malformed.

[  FAILED  ] GoogleUpdateRecoveryTest.VerifyFileSignature_SignedValid (8 ms)
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true
testing\unit_test.cc(238): error: System::StartProcessWithArgsAndInfo(app_launcher, cmd_line_args, &pi) failed with error 0x80070002
testing\unit_test.cc(241): error: Value of: started_process
  Actual: false
Expected: true
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expe [...]

2020-09-10 07:14 UTC, mherrmann commented
@simonhong @mihaiplesa wants me to look at something else first. I'll get back to you here.

2020-09-10 07:18 UTC, mherrmann commented
@simonhong actually Mihai asked me to look into this now, while you're still online. I'll report back here.

2020-09-10 07:24 UTC, mherrmann commented
Compiling my findings here.

-[ ] TimeTest.RFC822TimeParsing
-[ ] UserRightsTest.UserIsLoggedOnInteractively
-[ ] UtilsTest.ReadEntireFile
-[ ] UtilsTest.IsUserLoggedOn
-[ ] HelpUrlBuilderTest.BuildGetHelpUrl_User
-[ ] HelpUrlBuilderTest.BuildGetHelpUrl_Machine
-[ ] HelpUrlBuilderTest.BuildGetHelpUrl_InstallerErrorWithExtraCode
-[ ] HelpUrlBuilderTest.BuildGetHelpUrl_InstallerErrorWithoutExtraCode
-[ ] CommandLineBuilder.BuildUpdateAndGetCommandLineWithGoogleUpdateExe
-[ ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_ShellExists
-[ ] GoopdateUtilsTest.GetInstalledShellVersion_User_ShellExists
-[ ] GoopdateUtilsRegistryProtectedWithMachineFolderPathsTest.BuildGoogleUpdateExePath_MachineVersionFound
-[ ] GoopdateUtilsRegistryProtectedWithMachineFolderPathsTest.BuildGoogleUpdateExePath_MachineVersionNotFound
-[ ] GoopdateUtilsRegistryProtectedWithUserFolderPathsTest.BuildGoogleUpdateExePath_UserVersionFound
-[ ] GoopdateUtilsRegistryProtectedWithUserFolderPathsTest.BuildGoogleUpdateExePath_UserVersionNotFound
-[ ] OmahaCustomizationTest.Constants_BuildFiles
-[ ] OmahaCustomizationTest.Constants_Names
-[ ] OmahaCustomizationTest.Constants_Filenames
-[ ] OmahaCustomizationTest.Constants_OmahaAppId_String
-[ ] OmahaCustomizationTest.Constants_OmahaAppId_GUID
-[ ] OmahaCustomizationTest.Constants_MsiMsp
-[ ] OmahaCustomizationTest.Constants_Addresses
-[ ] OmahaCustomizationTest.Constants_Logging
-[ ] OmahaCustomizationTest.Constants_ObjectNames_MutexesAndEvents
-[ ] OmahaCustomizationTest.Constants_Services
-[ ] OmahaCustomizationTest.IsInternalUser
-[ ] PingEventDownloadMetricsTest.BuildPing
-[ ] PingTest.BuildOmahaPing
-[ ] PingTest.BuildAppsPing
-[ ] PingTest.SendInProcess
-[ ] PingTest.PersistAndSendPersistedPings
-[ ] WebServicesClientTest.Send
-[ ] WebServicesClientTest.SendForcingHttps
-[ ] WebServicesClientTest.SendWithCustomHeader
-[ ] WebServicesClientTest.SendStringWithCustomHeader
-[ ] AppBundlePopulatedRegistryUserTest.createInstalledApp_Present_TwoApps
-[ ] AppBundlePopulatedRegistryUserTest.createAllInstalledApps
-[ ] AppBundlePopulatedRegistryUserTest.createAllInstalledApps_InvalidPvValueType
-[ ] AppBundlePopulatedRegistryUserTest.createAllInstalledApps_ExternalUpdaterRunning
-[ ] AppBundlePopulatedRegistryMachineTest.createAllInstalledApps
-[ ] AppBundlePopulatedRegistryMachineTest.createAllInstalledApps_ExternalUpdaterRunning
-[ ] AppManagerReadAppPersistentDataMachineTest.ReadUninstalledAppPersistentData_UninstalledApp
-[ ] AppManagerReadAppPersistentDataMachineTest.ClientStateExistsWithoutPvOrClientsKey
-[ ] AppManagerReadAppPersistentDataUserTest.AppExists_NoDisplayName
-[ ] AppManagerReadAppPersistentDataUserTest.AppExists_EmptyDisplayName
-[ ] AppManagerReadAppPersistentDataUserTest.ReadUninstalledAppPersistentData_UninstalledApp
-[ ] AppManagerReadAppPersistentDataUserTest.ReadUninstalledAppPersistentData_EulaNotAccepted
-[ ] AppManagerReadAppPersistentDataUserTest.ClientStateExistsWithoutPvOrClientsKey
-[ ] AppManagerReadAppPersistentDataUserTest.ClientStateExistsWithEmptyPvNoClientsKey
-[ ] DownloadManagerUserTest.DownloadApp_MultiplePackagesInOneApp
-[ ] DownloadManagerTest.GetMessageForError
-[ ] InstallManagerInstallAppMachineTest.InstallApp_MsiInstallerSucceeds
-[ ] InstallManagerInstallAppMachineTest.InstallApp_MsiInstallerWithArgumentSucceeds
-[ ] InstallerWrapperMachineTest.InstallApp_MsiInstallerSucceeds
-[ ] InstallerWrapperMachineTest.InstallApp_MsiInstallerWithArgumentSucceeds
-[ ] WorkerWithTwoAppsTest.CheckForUpdateAsync_Large
-[ ] WorkerWithTwoAppsTest.DownloadAsyncThenDownloadAndInstallAsync_Large
-[ ] WorkerUtilsTest.FormatMessageForNetworkError
-[ ] CupEcdsaRequestTest.PostSimpleRequest
-[ ] CupEcdsaRequestTest.PostSimpleRequestHttps
-[ ] NetworkRequestTest.MultipleRequests
-[ ] GoogleUpdateRecoveryTest.VerifyFileSignature_SignedValid
-[ ] GoogleUpdateRecoveryTest.ProductionServerResponseTest
-[ ] SetupUserTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
-[ ] SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
-[ ] SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
-[ ] SetupMachineTest.StopGoogleUpdateAndWait_MachineHandoffWorkerRunningAsUser
-[ ] SetupMachineTest.StopGoogleUpdateAndWait_MachineLegacyInstallGoogleUpdateWorkerRunningAsUser
-[ ] SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem
-[ ] SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem
-[ ] SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
-[ ] SetupFilesUserTest.ShouldCopyShell_ExistingIsOlderButCompatible_1_2_131_7
-[ ] SetupFilesUserTest.ShouldCopyShell_ExistingIsOlderButCompatible_1_2_183_9
-[ ] SetupFilesUserTest.ShouldCopyShell_ExistingIsOlderMinor
-[ ] SetupFilesUserTest.ShouldCopyShell_ExistingIsOlderSameMinor
-[ ] SetupFilesUserTest.ShouldCopyShell_ExistingHasNoVersion
-[ ] SetupGoogleUpdateMachineTest.InstallRegistryValues
-[ ] SetupGoogleUpdateMachineTest.InstallMsiHelper_OverinstallDifferentMsiBuild
-[ ] ExecuteRepairFileTest.VerifyFileAndExecute_ValidRepairFileWithArgs
-[ ] ExecuteRepairFileTest.VerifyFileAndExecute_ValidRepairFileWithoutArgs
-[ ] RepairGoopdateWithMsiInstalledTest.ExecuteGoogleSignedExe_RepairFileDoesNotExist
-[ ] RepairGoopdateWithMsiInstalledTest.ExecuteGoogleSignedExe_UnsignedFile
-[ ] RepairGoopdateWithMsiInstalledTest.ExecuteGoogleSignedExe_ValidRepairFile
-[ ] RepairGoopdateWithoutMsiInstalledTest.ExecuteGoogleSignedExe_MsiNotInstalled
-[ ] RepairGoopdateTest.LaunchRepairFileElevated_MachineInstanceVistaWithMsiInstalledValidFile
-[ ] RepairGoopdateTest.LaunchRepairFileElevated_MachineInstanceVistaWithMsiInstalledBadFile
-[ ] RepairGoopdateTest.LaunchRepairFileElevated_MachineInstanceVistaWithoutMsiInstalled
-[ ] IsForeground/WebServicesClientTest.SendUsingCup/0, where GetParam() = false
-[ ] IsForeground/WebServicesClientTest.SendUsingCup/1, where GetParam() = true
-[ ] IsForeground/WebServicesClientTest.SendString/0, where GetParam() = false
-[ ] IsForeground/WebServicesClientTest.SendString/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AllValues_MachineApp/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AllValues_MachineApp/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AllValues_UserApp/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AllValues_UserApp/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_NoOmahaRegKeys/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_NoOmahaRegKeys/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_EmptyAppInfo/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_EmptyAppInfo/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsZeroDwordInHkcu/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsZeroDwordInHkcu/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsNonZeroDword/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsNonZeroDword/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsZeroDword64/0, where GetParam() = false
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsZeroDword64/1, where GetParam() = true
-[ ] IsDomain/GoogleUpdateRecoveryRegistryProtectedTest.FixGoogleUpdate_AutoUpdateCheckPeriodMinutesIsNonZeroDword [...]

2020-09-10 07:54 UTC, simonhong commented
I'll write down here the result of running each test. I think tests are sometimes flaky when we run all tests.
```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_filter=UtilsTest.ReadEntireFile
Note: Google Test filter = UtilsTest.ReadEntireFile
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from UtilsTest
[ RUN      ] UtilsTest.ReadEntireFile
[       OK ] UtilsTest.ReadEntireFile (1 ms)
[----------] 1 test from UtilsTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (5 ms total)
[  PASSED  ] 1 test.
```

2020-09-10 11:41 UTC, mherrmann commented
Summary of my [analysis of test failures](https://github.com/brave/omaha/pull/29#issuecomment-690045177):

The only failure that was obviously critical, `ReadEntireFile`, was likely spurious because as @simonhong reports [above](https://github.com/brave/omaha/pull/29#issuecomment-690060854) it passes when run as the only test.

That's not to say that everything is okay. For some of the tests, I simply do not know whether their failures are caused simply by Brave using (say) different UUIDs, or by actual functional problems. And even "superficial" test failures may hide functional problems. (So the test might fail because of a string constant, but then stops running before highlighting an actual functional regression.)

80% of tests can likely be fixed quite easily. As a very basic step, placing `psexec` on the path should already get rid of some failures. Fixing simple strings such as `GoogleUpdate.exe` instead of `BraveUpdate.exe` will also go a long way.

But there are also failures that will be harder to fix. Eg. `InstallMsiHelper_OverinstallDifferentMsiBuild` may require figuring out what a pre-compiled `GoogleUpdateHelper.msi` in Omaha's source tree actually does, then mimicking this for Brave.

I agree with @simonhong that it's likely not cost-effective to get to 0 test failures. I suspect it would take a week or two of full-time work.

My feeling is that the most risk lies in the area of MSI installers and patches. If Brave doesn't use or support MSI then we could get away with not looking into the related tests more closely.

I would suggest implementing the 80% of simple test fixes, then evaluating whether the remaining tests are likely to have an impact on Brave's important use cases.

2020-09-10 11:57 UTC, simonhong commented
@mherrmann Thanks for checking test results.
I agreed that we could have some more invisible failure hidden by simple string(uuid/branding) compare failure.
So, it's worth to fix those tests that can be easily fixed. I'll do that.
Regarding to MSI failures, we don't support it now. So, I think it's fine to ignore them.

2020-09-14 10:14 UTC, mherrmann commented
@simonhong do you have a list of remaining failing unit tests, so I can do another round of reviews?

2020-09-14 11:56 UTC, simonhong commented
@mherrmann This is current out of test run.
```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_brief=1

Pinging 2.2.2.2 with 32 bytes of data:

P
tPgiinnggi n2g. 22..22..22 .2 withw i3t2h  b3y2t ebsy toefs  doaft ad:a
:

P
tPgiinnggi n2g. 22..22..22 .2 withw i3t2h  b3y2t ebsy toefs  doaft ad:a
:

Pinging 2.2.2.2 with 32 bytes of data:
base\time_unittest.cc(143): error: Expected equality of these values:
  time.wDay
    Which is: 17
  16
[  FAILED  ] TimeTest.RFC822TimeParsing (1 ms)
base\user_rights_unittest.cc(28): error: Expected: (UserRights::UserIsLoggedOnInteractively(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

base\user_rights_unittest.cc(29): error: Value of: is_logged_on
  Actual: false
Expected: true
[  FAILED  ] UserRightsTest.UserIsLoggedOnInteractively (7 ms)
        This test needs to be run separately. Set 'TEST_GETFOLDERPATH_PROGRAMFILES_REGISTRYREDIRECTION' in the environment, then run it separately.
base\utils_unittest.cc(383): error: Expected: (IsUserLoggedOn(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

[  FAILED  ] UtilsTest.IsUserLoggedOn (2 ms)
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because OS is Vista or later.
common\goopdate_utils_unittest.cc(1218): error: Expected equality of these values:
  shell_version
    Which is: 281487868231680
  0ULL
    Which is: 0
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell (1 ms)
common\goopdate_utils_unittest.cc(1228): error: File::Copy(shell_path_1_2_183_21, goopdate_exe, true) failed with error 0x80070020
common\goopdate_utils_unittest.cc(1231): error: File::Remove(goopdate_exe) failed with error 0x80070005
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_ShellExists (42 ms)
        Test did not run because the user IS an admin.
common\ping_test.cc(136): error: Expected: (-1) != (actual_ping_request.Find(expected_shell_version_substring)), actual: -1 vs -1
[  FAILED  ] PingTest.BuildOmahaPing (46 ms)
common\ping_test.cc(253): error: Expected: (install_ping.SendInProcess(request_string)) succeeds.
  Actual: 0x80042190

[  FAILED  ] PingTest.SendInProcess (909 ms)
common\ping_test.cc(359): error: Expected equality of these values:
  0
  pings_reg_key.GetSubkeyCount()
    Which is: 1
[  FAILED  ] PingTest.PersistAndSendPersistedPings (1329 ms)
        Test did not run because this OS supports the Task Scheduler 2.0 API.
common\web_services_client_unittest.cc(90): error: Expected: (web_service_client_->Send(false, update_request_.get(), update_response_.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(91): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
common\web_services_client_unittest.cc(94): error: Expected equality of these values:
  L"3.0"
  response.protocol
    Which is: L""
[  FAILED  ] WebServicesClientTest.Send (1463 ms)
common\web_services_client_unittest.cc(223): error: Expected: (web_service_client_->Send(false, update_request_.get(), update_response_.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(224): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
common\web_services_client_unittest.cc(240): error: Expected equality of these values:
  L"3.0"
  response.protocol
    Which is: L""
common\web_services_client_unittest.cc(241): error: Expected equality of these values:
  2
  response.apps.size()
    Which is: 0
[  FAILED  ] WebServicesClientTest.SendForcingHttps (715 ms)
common\web_services_client_unittest.cc(256): error: Expected: (web_service_client_->Send(false, update_request_.get(), update_response_.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(257): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
common\web_services_client_unittest.cc(260): error: Expected equality of these values:
  L"3.0"
  response.protocol
    Which is: L""
[  FAILED  ] WebServicesClientTest.SendWithCustomHeader (626 ms)
common\web_services_client_unittest.cc(324): error: Expected: (web_service_client_->SendString(false, &request_string, response.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(325): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
[  FAILED  ] WebServicesClientTest.SendStringWithCustomHeader (971 ms)
Hello World
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test is only meaningful when the unit test is run as the SYSTEM account.
goopdate\download_manager_unittest.cc(216): error: Expected: (-1) != (actual_pings.Find( L"eventtype=1, eventresult=1, errorcode=0, extracode1=0, " L"url=http://dl.google.com/update2/UpdateData.bin, " L"downloader=bits, error=0x0, downloaded_bytes=2048, " L"total_bytes=2048, download_time=")), actual: -1 vs -1
goopdate\download_manager_unittest.cc(222): error: Expected: (-1) != (actual_pings.Find( L"eventtype=1, eventresult=1, errorcode=0, extracode1=0, " L"url=http://dl.google.com/update2/UpdateData1.bin, " L"downloader=bits, error=0x0, downloaded_bytes=2048, " L"total_bytes=2048, download_time=")), actual: -1 vs -1
[  FAILED  ] DownloadManagerUserTest.DownloadApp_MultiplePackagesInOneApp (990 ms)
The operation completed successfully.
goopdate\install_manager_unittest.cc(641): error: InstallApp(L"", app_, installer_dir) failed with error 0x80040905
goopdate\install_manager_unittest.cc(643): error: Expected equality of these values:
  STATE_INSTALL_COMPLETE
    Which is: 14
  app_->state()
    Which is: 17
goopdate\install_manager_unittest.cc(644): error: Expected equality of these values:
  PingEvent::EVENT_RESULT_SUCCESS
    Which is: 1
  GetCompletionResult(app_)
    Which is: 0
goopdate\install_manager_unittest.cc(645): error: Expected equality of these values:
  ((HRESULT)0L)
    Which is: 0
  GetResultCode(app_)
    Which is: -2147219195
goopdate\install_manager_unittest.cc(647): error: Expected equality of these values:
  L"Thanks for installing."
  GetCompletionMessage(app_)
    Which is: L"Installation failed. Please try again."
goopdate\install_manager_unittest.cc(654): error: Value of: RegKey::HasKey(kFullFooAppClientKeyPath)
  Actual: false
Expected: true
goopdate\install_manager_unittest.cc(655): error: Value of: RegKey::HasKey(kFullFooAppClientStateKeyPath)
  Actual: false
Expected: true
goopdate\install_manager_unittest.cc(657): error: state_key.Open(kFullFooAppClientStateKeyPath) failed with error 0x80070002
C:\PRJ\omaha-new\omaha/testing/unittest_debug_helper.h(74): error: Failed
ASSERT in base\reg_key.cc(1148): h_key_; ""
C:\PRJ\omaha-new\omaha/testing/unittest_debug_helper.h(74): error: Failed
ASSERT in base\reg_key.cc(1165): res == 0L; ""
goopdate\install_manager_unittest.cc(658): error: Expected equality of these values:
  4 + kNumAutoPopulatedValues
    Which is: 11
  state_key.GetValueCount()
    Which is: 0
testing\unit_test.cc(91): error: RegKey::GetValue(full_key_name, value_name, &value) failed with error 0x80070002
goopdate\install_manager_unittest.cc(660): error: Expected equality of these values:
  kFooVersion
    Which is: L"1.0.101.0"
  GetSzValue(kFullFooAppClientStateKeyPath, kRegValueProductVersion)
  [...]

2020-09-14 12:27 UTC, mherrmann commented
My review notes.

- [x] `TimeTest.RFC822TimeParsing` ; probably fails because Simon's timezone is not PST. Try running with timezone set to PST?
- [ ] `UserRightsTest.UserIsLoggedOnInteractively`
- [ ] `UtilsTest.IsUserLoggedOn`
- [ ] `GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell`
- [ ] `GoopdateUtilsTest.GetInstalledShellVersion_Machine_ShellExists`
- [ ] `PingTest.BuildOmahaPing`
- [ ] `PingTest.SendInProcess`
- [ ] `PingTest.PersistAndSendPersistedPings`
- [ ] `WebServicesClientTest.Send`
- [ ] `WebServicesClientTest.SendForcingHttps`
- [ ] `WebServicesClientTest.SendWithCustomHeader`
- [ ] `WebServicesClientTest.SendStringWithCustomHeader`
- [ ] `DownloadManagerUserTest.DownloadApp_MultiplePackagesInOneApp`
- [ ] `InstallManagerInstallAppMachineTest.InstallApp_MsiInstallerSucceeds`
- [ ] `InstallManagerInstallAppMachineTest.InstallApp_MsiInstallerWithArgumentSucceeds`
- [ ] `InstallerWrapperMachineTest.InstallApp_MsiInstallerSucceeds`
- [ ] `InstallerWrapperMachineTest.InstallApp_MsiInstallerWithArgumentSucceeds`
- [ ] `WorkerWithTwoAppsTest.CheckForUpdateAsync_Large`
- [ ] `WorkerWithTwoAppsTest.DownloadAsyncThenDownloadAndInstallAsync_Large`
- [ ] `CupEcdsaRequestTest.PostSimpleRequest`
- [ ] `CupEcdsaRequestTest.PostSimpleRequestHttps`
- [ ] `NetworkRequestTest.MultipleRequests`
- [ ] `GoogleUpdateRecoveryTest.FixGoogleUpdate_FileReturned_Machine`
- [ ] `GoogleUpdateRecoveryTest.FixGoogleUpdate_FileReturned_User`
- [ ] `GoogleUpdateRecoveryTest.FixGoogleUpdate_FileCollision`
- [ ] `GoogleUpdateRecoveryTest.VerifyFileSignature_SignedValid`
- [ ] `GoogleUpdateRecoveryTest.ProductionServerResponseTest`
- [ ] `SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess`
- [ ] `SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop`
- [ ] `SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem`
- [ ] `SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem`
- [ ] `SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess`
- [ ] `SetupGoogleUpdateMachineTest.InstallMsiHelper_OverinstallDifferentMsiBuild`
- [ ] `ExecuteRepairFileTest.VerifyFileAndExecute_ValidRepairFileWithArgs`
- [ ] `ExecuteRepairFileTest.VerifyFileAndExecute_ValidRepairFileWithoutArgs`
- [ ] `RepairGoopdateWithMsiInstalledTest.ExecuteGoogleSignedExe_RepairFileDoesNotExist`
- [ ] `RepairGoopdateWithMsiInstalledTest.ExecuteGoogleSignedExe_UnsignedFile`
- [ ] `RepairGoopdateWithMsiInstalledTest.ExecuteGoogleSignedExe_ValidRepairFile`
- [ ] `RepairGoopdateWithoutMsiInstalledTest.ExecuteGoogleSignedExe_MsiNotInstalled`
- [ ] `RepairGoopdateTest.LaunchRepairFileElevated_MachineInstanceVistaWithMsiInstalledValidFile`
- [ ] `RepairGoopdateTest.LaunchRepairFileElevated_MachineInstanceVistaWithMsiInstalledBadFile`
- [ ] `RepairGoopdateTest.LaunchRepairFileElevated_MachineInstanceVistaWithoutMsiInstalled`
- [ ] `IsForeground/WebServicesClientTest.SendUsingCup/0`
- [ ] `IsForeground/WebServicesClientTest.SendUsingCup/1`
- [ ] `IsForeground/WebServicesClientTest.SendString/0`
- [ ] `IsForeground/WebServicesClientTest.SendString/1`
- [ ] `IsMachine/InstallManagerTest.InstallDir_ReadOnlyFiles/1`

2020-09-14 13:56 UTC, mherrmann commented
@simonhong I'm trying to figure out what has changed since my [previous analysis](https://github.com/brave/omaha/pull/29#issuecomment-690045177). Do you remember which git revision [your output](https://github.com/brave/omaha/pull/29#issuecomment-690026926) was based on? You force-pushed a few times so I don't know whether I can trust the revisions that are in the repo now.

2020-09-14 14:21 UTC, simonhong commented
@mherrmann Yes, https://github.com/brave/omaha/commit/4c8cad84d4a03ba6a3f242b05f66688feec82bdd is correct

2020-09-14 14:23 UTC, mherrmann commented
Thanks! Could it be that `SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess` failed because `psexec` wasn't available?

2020-09-14 15:15 UTC, mherrmann requested changes
Summary of my [analysis](https://github.com/brave/omaha/pull/29#issuecomment-692019457) of the latest changes.

The number of failing tests is down to 47 from 131 thanks to @simonhong. Upstream, 21 tests fail. There are ~3,500 tests in total.

I'm still unsure about the following tests:

* SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
* SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
* SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem
* SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem
* SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess

My best explanation is that they failed because `psexec` wasn't on the `PATH`. I suggest @simonhong look into whether `psexec` was on the `PATH` and if not add it and run the tests again.

The other test failures don't pose a significant risk, as far as I can tell.

Once we have ruled out that the above tests highlight significant issues, I think it would be fine to merge into master, test carefully and if everything continues to seem fine slowly release to users.

2020-09-15 00:57 UTC, simonhong commented
I got this after adding pstools to path.

```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_filter=SetupUserTest*
Note: Google Test filter = SetupUserTest*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from SetupUserTest
[ RUN      ] SetupUserTest.Install_LockTimedOut
[       OK ] SetupUserTest.Install_LockTimedOut (1035 ms)
[ RUN      ] SetupUserTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
[       OK ] SetupUserTest.StopGoogleUpdateAndWait_ProcessesDoNotStop (2038 ms)
[ RUN      ] SetupUserTest.TerminateCoreProcesses_NoneRunning
[       OK ] SetupUserTest.TerminateCoreProcesses_NoneRunning (11 ms)
[ RUN      ] SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 10168.
[  FAILED  ] SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess (1442 ms)
[----------] 4 tests from SetupUserTest (4533 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (4566 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SetupUserTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess

 1 FAILED TEST
  YOU HAVE 1 DISABLED TEST


C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_filter=SetupMachineTest*
Note: Google Test filter = SetupMachineTest*
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from SetupMachineTest
[ RUN      ] SetupMachineTest.Install_LockTimedOut
[       OK ] SetupMachineTest.Install_LockTimedOut (1022 ms)
[ RUN      ] SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 1840.
[  FAILED  ] SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop (2390 ms)
[ RUN      ] SetupMachineTest.StopGoogleUpdateAndWait_MachineHandoffWorkerRunningAsUser
[       OK ] SetupMachineTest.StopGoogleUpdateAndWait_MachineHandoffWorkerRunningAsUser (2023 ms)
[ RUN      ] SetupMachineTest.StopGoogleUpdateAndWait_MachineLegacyInstallGoogleUpdateWorkerRunningAsUser
[       OK ] SetupMachineTest.StopGoogleUpdateAndWait_MachineLegacyInstallGoogleUpdateWorkerRunningAsUser (2037 ms)
[ RUN      ] SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 4208.
[  FAILED  ] SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem (2402 ms)
[ RUN      ] SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 2144.
[  FAILED  ] SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem (2386 ms)
[ RUN      ] SetupMachineTest.TerminateCoreProcesses_NoneRunning
[       OK ] SetupMachineTest.TerminateCoreProcesses_NoneRunning (11 ms)
[ RUN      ] SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 6096.
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 6004.
testing\unit_test.cc(164): error: Value of: _tcsnlen(psexec_dir, arraysize(psexec_dir))
  Actual: false
Expected: true

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\Program Files (x86)\BraveSoftware\Update\does_not_shutdown\BraveUpdate.exe started on DESKTOP-A7HR52H with process ID 2924.
[  FAILED  ] SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess (2081 ms)
[----------] 8 tests from SetupMachineTest (14366 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test suite ran. (14386 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] SetupMachineTest.StopGoogleUpdateAndWait_ProcessesDoNotStop
[  FAILED  ] SetupMachineTest.StopGoogleUpdateAndWait_UserHandoffWorkerRunningAsSystem
[  FAILED  ] SetupMachineTest.StopGoogleUpdateAndWait_UserLegacyInstallGoogleUpdateWorkerRunningAsSystem
[  FAILED  ] SetupMachineTest.TerminateCoreProcesses_BothTypesRunningAndSimilarArgsProcess

 4 FAILED TESTS
  YOU HAVE 1 DISABLED TEST


C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>
```

2020-09-15 01:45 UTC, simonhong commented
Passed `TimeTest.RFC822TimeParsing` with `PST`.
```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_filter=TimeTest.RFC822TimeParsing
Note: Google Test filter = TimeTest.RFC822TimeParsing
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TimeTest
[ RUN      ] TimeTest.RFC822TimeParsing
[       OK ] TimeTest.RFC822TimeParsing (0 ms)
[----------] 1 test from TimeTest (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (8 ms total)
[  PASSED  ] 1 test.
```

2020-09-15 01:51 UTC, simonhong commented
Passed `GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell`. I assume this is intermittent failure.
```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_filter=GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell
Note: Google Test filter = GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from GoopdateUtilsTest
[ RUN      ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell
[       OK ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell (7 ms)
[----------] 1 test from GoopdateUtilsTest (8 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (14 ms total)
[  PASSED  ] 1 test.

C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>
```

2020-09-15 01:58 UTC, simonhong commented
Hmm, below two tests still have same failure. I think we can ignore these failure also because upstream also have same failure.
*  `omaha_unittest.exe --gtest_filter=UserRightsTest.UserIsLoggedOnInteractively`
* `omaha_unittest.exe --gtest_filter=UtilsTest.IsUserLoggedOn`

2020-09-15 06:47 UTC, mherrmann commented
@simonhong I mistakenly wrote "put `psexec` on the `PATH`". But should have been "set `OMAHA_PSEXEC_DIR` to the directory containing `psexec`" as described in the [docs](https://github.com/google/omaha/blob/master/doc/DeveloperSetupGuide.md#running-unit-tests).

It may be a stupid question, for which I apologise, but just to confirm: Did you set `OMAHA_PSEXEC_DIR`?

2020-09-15 07:07 UTC, simonhong commented
Test result with pstools env setting.

```
C:\PRJ\omaha-new\omaha\scons-out\dbg-win\staging>omaha_unittest.exe --gtest_brief=1

Pinging 2.2.2.2 with 32 bytes of data:

gingin
fP.i2n.g2i.n2g  2.2w.i2t.h2  32 bywtietsh  o3f2  dbytaetsa :o
data:

gin
aPgi n2g.i2n.g2 .22. 2.2.2w ith w3i2t hb y3t2e sb yotfe sd aotfa :d
a:

Pinging 2.2.2.2 with 32 bytes of data:
base\time_unittest.cc(143): error: Expected equality of these values:
  time.wDay
    Which is: 17
  16
[  FAILED  ] TimeTest.RFC822TimeParsing (1 ms)
base\user_rights_unittest.cc(28): error: Expected: (UserRights::UserIsLoggedOnInteractively(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

base\user_rights_unittest.cc(29): error: Value of: is_logged_on
  Actual: false
Expected: true
[  FAILED  ] UserRightsTest.UserIsLoggedOnInteractively (10 ms)
base\utils_unittest.cc(113): error: Expected equality of these values:
  ((HRESULT)1L)
    Which is: 1
  GetFolderPath(0x0026, &path)
    Which is: 0
[  FAILED  ] UtilsTest.GetFolderPath_ProgramFiles_RegistryRedirection (1 ms)
base\utils_unittest.cc(383): error: Expected: (IsUserLoggedOn(&is_logged_on)) succeeds.
  Actual: 0x80004005 Unspecified error

[  FAILED  ] UtilsTest.IsUserLoggedOn (1 ms)
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Skipping test because user is elevated with UAC on.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because the user IS an admin.
        Test did not run because OS is Vista or later.
common\goopdate_utils_unittest.cc(1218): error: Expected equality of these values:
  shell_version
    Which is: 281487868231680
  0ULL
    Which is: 0
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_NoShell (1 ms)
common\goopdate_utils_unittest.cc(1228): error: File::Copy(shell_path_1_2_183_21, goopdate_exe, true) failed with error 0x80070020
common\goopdate_utils_unittest.cc(1231): error: File::Remove(goopdate_exe) failed with error 0x80070005
[  FAILED  ] GoopdateUtilsTest.GetInstalledShellVersion_Machine_ShellExists (43 ms)
        Test did not run because the user IS an admin.
common\ping_test.cc(136): error: Expected: (-1) != (actual_ping_request.Find(expected_shell_version_substring)), actual: -1 vs -1
[  FAILED  ] PingTest.BuildOmahaPing (45 ms)
common\ping_test.cc(253): error: Expected: (install_ping.SendInProcess(request_string)) succeeds.
  Actual: 0x80042190

[  FAILED  ] PingTest.SendInProcess (1254 ms)
common\ping_test.cc(359): error: Expected equality of these values:
  0
  pings_reg_key.GetSubkeyCount()
    Which is: 1
[  FAILED  ] PingTest.PersistAndSendPersistedPings (1591 ms)
        Test did not run because this OS supports the Task Scheduler 2.0 API.
common\web_services_client_unittest.cc(90): error: Expected: (web_service_client_->Send(false, update_request_.get(), update_response_.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(91): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
common\web_services_client_unittest.cc(94): error: Expected equality of these values:
  L"3.0"
  response.protocol
    Which is: L""
[  FAILED  ] WebServicesClientTest.Send (976 ms)
common\web_services_client_unittest.cc(223): error: Expected: (web_service_client_->Send(false, update_request_.get(), update_response_.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(224): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
common\web_services_client_unittest.cc(240): error: Expected equality of these values:
  L"3.0"
  response.protocol
    Which is: L""
common\web_services_client_unittest.cc(241): error: Expected equality of these values:
  2
  response.apps.size()
    Which is: 0
[  FAILED  ] WebServicesClientTest.SendForcingHttps (682 ms)
common\web_services_client_unittest.cc(256): error: Expected: (web_service_client_->Send(false, update_request_.get(), update_response_.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(257): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
common\web_services_client_unittest.cc(260): error: Expected equality of these values:
  L"3.0"
  response.protocol
    Which is: L""
[  FAILED  ] WebServicesClientTest.SendWithCustomHeader (610 ms)
common\web_services_client_unittest.cc(324): error: Expected: (web_service_client_->SendString(false, &request_string, response.get())) succeeds.
  Actual: 0x80042190

common\web_services_client_unittest.cc(325): error: Value of: web_service_client_->is_http_success()
  Actual: false
Expected: true
[  FAILED  ] WebServicesClientTest.SendStringWithCustomHeader (1336 ms)
Hello World
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test did not run because 'OMAHA_TEST_UI' is not set in the environment.
        This test is only meaningful when the unit test is run as the SYSTEM account.
goopdate\download_manager_unittest.cc(216): error: Expected: (-1) != (actual_pings.Find( L"eventtype=1, eventresult=1, errorcode=0, extracode1=0, " L"url=http://dl.google.com/update2/UpdateData.bin, " L"downloader=bits, error=0x0, downloaded_bytes=2048, " L"total_bytes=2048, download_time=")), actual: -1 vs -1
goopdate\download_manager_unittest.cc(222): error: Expected: (-1) != (actual_pings.Find( L"eventtype=1, eventresult=1, errorcode=0, extracode1=0, " L"url=http://dl.google.com/update2/UpdateData1.bin, " L"downloader=bits, error=0x0, downloaded_bytes=2048, " L"total_bytes=2048, download_time=")), actual: -1 vs -1
[  FAILED  ] DownloadManagerUserTest.DownloadApp_MultiplePackagesInOneApp (1016 ms)
The operation completed successfully.
goopdate\install_manager_unittest.cc(641): error: InstallApp(L"", app_, installer_dir) failed with error 0x80040905
goopdate\install_manager_unittest.cc(643): error: Expected equality of these values:
  STATE_INSTALL_COMPLETE
    Which is: 14
  app_->state()
    Which is: 17
goopdate\install_manager_unittest.cc(644): error: Expected equality of these values:
  PingEvent::EVENT_RESULT_SUCCESS
    Which is: 1
  GetCompletionResult(app_)
    Which is: 0
goopdate\install_manager_unittest.cc(645): error: Expected equality of these values:
  ((HRESULT)0L)
    Which is: 0
  GetResultCode(app_)
    Which is: -2147219195
goopdate\install_manager_unittest.cc(647): error: Expected equality of these values:
  L"Thanks for installing."
  GetCompletionMessage(app_)
    Which is: L"Installation failed. Please try again."
goopdate\install_manager_unittest.cc(654): error: Value of: RegKey::HasKey(kFullFooAppClientKeyPath)
  Actual: false
Expected: true
goopdate\install_manager_unittest.cc(655): error: Value of: RegKey::HasKey(kFullFooAppClientStateKeyPath)
  Actual: false
Expected: true
goopdate\install_manager_unittest.cc(657): error: state_key.Open(kFullFooAppClientStateKeyPath) failed with error 0x80070002
C:\PRJ\omaha-new\omaha/testing/unittest_debug_helper.h(74): error: Failed
ASSERT in base\reg_key.cc(1148): h_key_; ""
C:\PRJ\omaha-new\omaha/testing/unittest_debug_helper.h(74): error: Failed
ASSERT in base\reg_key.cc(1165): res == 0L; ""
goopdate\install_manager_unittest.cc(658): error: Expected equality of these values:
  4 + kNumAutoPopulatedValues
    Which is: 11
  state_key.GetValueCount()
    Which is: 0
testing\unit_test.cc(91): error: RegKey::GetValue(full_key_name, value_name, &value) failed with error 0x80070002
goopdate\install_manager_unittest.cc(660): error: Expected equality of these values:
  kFooVersion
    Which is: L"1.0.10 [...]

2020-09-15 07:14 UTC, mherrmann commented
The output from @simonhong's [latest run](https://github.com/brave/omaha/pull/29#issuecomment-692513375) shows that the [five tests I was still unsure about](https://github.com/brave/omaha/pull/29#pullrequestreview-487878382) pass.

From my perspective, we can proceed to merge, test carefully and release slowly.

2020-09-21 10:11 UTC, mherrmann approved these changes
Good to merge from my POV.

2020-09-25 09:55 UTC, mihaiplesa commented
Closing as we created a new default branch named `main` off this so it's all in.

2020-09-25 09:55 UTC, closed without merging